version: "3.3"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
    prometheus: {}

configs:
  prometheus_rules:
    file: ./prometheus.yml

services:
  prometheus:
    image: prom/prometheus:v2.2.0-rc.0 
    ports:
      - "9090:9090"
    networks:
      - net
    configs:
      - source: prometheus_rules 
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M

  consul:
    image: consul
    ports:
      - "8500:8500"    
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter-1:
    image: prom/node-exporter:v0.15.2
    ports:
      - "9100:9100"    
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter-2:
    image: prom/node-exporter:v0.15.2
    ports:
      - "9101:9100"    
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter-3:
    image: prom/node-exporter:v0.15.2
    ports:
      - "9102:9100"    
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M