global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'consul-services'
    consul_sd_configs:
    - server:   'consul:8500'
    relabel_configs:
    - source_labels: ['__meta_consul_service']
      action: drop
      regex: consul
    - source_labels: ['__meta_consul_tags']
      action: keep
      regex: '.*,(Nginx),.*' 
      replacement: '${1}'